2015/09/15 15:02:11 [error] [exception.CException] exception 'CException' with message 'ApiController and its behaviors do not have a method or closure named "sendResponse".' in Z:\home\blog\www\framework\base\CComponent.php:266
Stack trace:
#0 Z:\home\blog\www\protected\controllers\ApiController.php(28): CComponent->__call('sendResponse', Array)
#1 Z:\home\blog\www\protected\controllers\ApiController.php(28): ApiController->sendResponse(200, 'null')
#2 Z:\home\blog\www\framework\web\actions\CInlineAction.php(49): ApiController->actionTest()
#3 Z:\home\blog\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\home\blog\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\home\blog\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\home\blog\www\framework\web\CWebApplication.php(282): CController->run('test')
#7 Z:\home\blog\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/test')
#8 Z:\home\blog\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\home\blog\www\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=api/test&view=about
---
2015/09/15 15:02:23 [error] [exception.CException] exception 'CException' with message 'ApiController and its behaviors do not have a method or closure named "sendResponse".' in Z:\home\blog\www\framework\base\CComponent.php:266
Stack trace:
#0 Z:\home\blog\www\protected\controllers\ApiController.php(28): CComponent->__call('sendResponse', Array)
#1 Z:\home\blog\www\protected\controllers\ApiController.php(28): ApiController->sendResponse(200, 0)
#2 Z:\home\blog\www\framework\web\actions\CInlineAction.php(49): ApiController->actionTest()
#3 Z:\home\blog\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\home\blog\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\home\blog\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\home\blog\www\framework\web\CWebApplication.php(282): CController->run('test')
#7 Z:\home\blog\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/test')
#8 Z:\home\blog\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\home\blog\www\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=api/test&category=phones
---
2015/09/15 15:12:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "about".' in Z:\home\blog\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\blog\www\framework\web\CWebApplication.php(141): CWebApplication->runController('about')
#1 Z:\home\blog\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\blog\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/about
---
2015/09/15 15:12:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "about".' in Z:\home\blog\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\blog\www\framework\web\CController.php(270): CController->missingAction('about')
#1 Z:\home\blog\www\framework\web\CWebApplication.php(282): CController->run('about')
#2 Z:\home\blog\www\framework\web\CWebApplication.php(141): CWebApplication->runController('site/about')
#3 Z:\home\blog\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\blog\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/site/about
---
2015/09/15 15:12:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "index" was not found.' in Z:\home\blog\www\framework\web\actions\CViewAction.php:112
Stack trace:
#0 Z:\home\blog\www\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('index')
#1 Z:\home\blog\www\framework\web\actions\CAction.php(76): CViewAction->run()
#2 Z:\home\blog\www\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 Z:\home\blog\www\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 Z:\home\blog\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 Z:\home\blog\www\framework\web\CWebApplication.php(282): CController->run('page')
#6 Z:\home\blog\www\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 Z:\home\blog\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\home\blog\www\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/site/page
---
2015/09/15 15:12:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "index" was not found.' in Z:\home\blog\www\framework\web\actions\CViewAction.php:112
Stack trace:
#0 Z:\home\blog\www\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('index')
#1 Z:\home\blog\www\framework\web\actions\CAction.php(76): CViewAction->run()
#2 Z:\home\blog\www\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 Z:\home\blog\www\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 Z:\home\blog\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 Z:\home\blog\www\framework\web\CWebApplication.php(282): CController->run('page')
#6 Z:\home\blog\www\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page/about')
#7 Z:\home\blog\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\home\blog\www\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/site/page/about
---
2015/09/15 15:57:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/style.css".' in Z:\home\blog\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\blog\www\framework\web\CWebApplication.php(141): CWebApplication->runController('css/style.css')
#1 Z:\home\blog\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\blog\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/style.css
HTTP_REFERER=http://blog/site/index
---
2015/09/15 15:57:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/style.css".' in Z:\home\blog\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\blog\www\framework\web\CWebApplication.php(141): CWebApplication->runController('css/style.css')
#1 Z:\home\blog\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\blog\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/style.css
HTTP_REFERER=http://blog/site/index
---
2015/09/15 15:57:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/style.css".' in Z:\home\blog\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\blog\www\framework\web\CWebApplication.php(141): CWebApplication->runController('css/style.css')
#1 Z:\home\blog\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\blog\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/style.css
HTTP_REFERER=http://blog/css/style.css
---
2015/09/16 10:00:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://sitioblog.com/
---
2015/09/16 10:47:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://sitioblog.com/
---
2015/09/16 10:47:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://sitioblog.com/
---
2015/09/16 10:57:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/pic.png".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('images/pic.png')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/images/pic.png
HTTP_REFERER=http://sitioblog.com/
---
2015/09/16 11:15:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "images".' in Z:\home\sitioblog.com\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(270): CController->missingAction('images')
#1 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('images')
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/pic...')
#3 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/site/images/pic.png
HTTP_REFERER=http://sitioblog.com/site/login
---
2015/09/16 11:15:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "images".' in Z:\home\sitioblog.com\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(270): CController->missingAction('images')
#1 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('images')
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/pic...')
#3 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/site/images/pic.png
HTTP_REFERER=http://sitioblog.com/site/index
---
2015/09/16 11:15:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "images".' in Z:\home\sitioblog.com\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(270): CController->missingAction('images')
#1 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('images')
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/pic...')
#3 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/site/images/pic.png
HTTP_REFERER=http://sitioblog.com/site/login
---
2015/09/16 11:15:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "images".' in Z:\home\sitioblog.com\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(270): CController->missingAction('images')
#1 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('images')
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/pic...')
#3 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/site/images/pic.png
HTTP_REFERER=http://sitioblog.com/site/login
---
2015/09/16 11:15:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "images".' in Z:\home\sitioblog.com\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(270): CController->missingAction('images')
#1 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('images')
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/pic...')
#3 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/site/images/pic.png
HTTP_REFERER=http://sitioblog.com/site/index
---
2015/09/16 11:16:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "images".' in Z:\home\sitioblog.com\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(270): CController->missingAction('images')
#1 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('images')
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/pic...')
#3 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/site/images/pic.png
HTTP_REFERER=http://sitioblog.com/site/index
---
2015/09/16 12:21:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "phones".' in Z:\home\sitioblog.com\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(270): CController->missingAction('phones')
#1 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('phones')
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/phones')
#3 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/api/phones
---
2015/09/16 15:50:44 [error] [php] include(ActiveRecord.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\sitioblog.com\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\sitioblog.com\www\protected\models\User.php(6): spl_autoload_call()
#1 Z:\home\sitioblog.com\www\framework\YiiBase.php(432): include()
#2 unknown(0): autoload()
#3 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(28): spl_autoload_call()
#4 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionPage()
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#7 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#9 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/page?id=settgins
in Z:\home\sitioblog.com\www\protected\models\User.php (6)
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (28)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/16 15:50:50 [error] [php] include(ActiveRecord.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\sitioblog.com\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\sitioblog.com\www\protected\models\User.php(6): spl_autoload_call()
#1 Z:\home\sitioblog.com\www\framework\YiiBase.php(432): include()
#2 unknown(0): autoload()
#3 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(28): spl_autoload_call()
#4 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionPage()
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#7 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#9 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/page?id=settgins
in Z:\home\sitioblog.com\www\protected\models\User.php (6)
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (28)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/16 15:55:17 [error] [php] include(ActiveRecord.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\sitioblog.com\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\sitioblog.com\www\protected\models\User.php(6): spl_autoload_call()
#1 Z:\home\sitioblog.com\www\framework\YiiBase.php(432): include()
#2 unknown(0): autoload()
#3 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(28): spl_autoload_call()
#4 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionPage()
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#7 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#9 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/page?id=settgins
in Z:\home\sitioblog.com\www\protected\models\User.php (6)
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (28)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/16 15:56:10 [error] [php] Object of class User could not be converted to string (Z:\home\sitioblog.com\www\protected\controllers\ApiController.php:29)
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#1 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#3 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#5 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/page?id=settgins
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (29)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/16 15:56:29 [error] [php] include(ActiveRecord.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\sitioblog.com\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\sitioblog.com\www\protected\models\User.php(6): spl_autoload_call()
#1 Z:\home\sitioblog.com\www\framework\YiiBase.php(432): include()
#2 unknown(0): autoload()
#3 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(28): spl_autoload_call()
#4 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionPage()
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#7 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#9 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/page?id=settgins
in Z:\home\sitioblog.com\www\protected\models\User.php (6)
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (28)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/16 15:57:40 [error] [php] Object of class User could not be converted to string (Z:\home\sitioblog.com\www\protected\controllers\ApiController.php:29)
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#1 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#3 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#5 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/page?id=settgins
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (29)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/16 16:01:25 [error] [exception.CException] exception 'CException' with message 'Property "User.toJSON" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('toJSON')
#1 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(28): CActiveRecord->__get('toJSON')
#2 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionPage()
#3 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('page')
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/page')
#8 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/api/page?id=settgins
HTTP_REFERER=http://sitioblog.com/
---
2015/09/16 16:01:58 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "toJSON".' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:266
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(227): CComponent->__call('toJSON', Array)
#1 Z:\home\sitioblog.com\www\protected\models\User.php(20): CActiveRecord->__call('toJSON', Array)
#2 Z:\home\sitioblog.com\www\protected\models\User.php(20): CActiveRecord->toJSON()
#3 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(28): User->toJSON()
#4 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionPage()
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('page')
#9 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/page')
#10 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/api/page?id=settgins
HTTP_REFERER=http://sitioblog.com/
---
2015/09/16 16:04:55 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "toJSON".' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:266
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(227): CComponent->__call('toJSON', Array)
#1 Z:\home\sitioblog.com\www\protected\models\User.php(20): CActiveRecord->__call('toJSON', Array)
#2 Z:\home\sitioblog.com\www\protected\models\User.php(20): CActiveRecord->toJSON()
#3 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(29): User->toJSON()
#4 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionPage()
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('page')
#9 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/page')
#10 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/api/page?id=settgins
HTTP_REFERER=http://sitioblog.com/
---
2015/09/16 16:24:28 [error] [exception.CException] exception 'CException' with message 'Property "CDbCriteria.author" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:173
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\schema\CDbCriteria.php(160): CComponent->__set('author', 1)
#1 Z:\home\sitioblog.com\www\framework\db\schema\CDbCommandBuilder.php(588): CDbCriteria->__construct(Array)
#2 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(1474): CDbCommandBuilder->createCriteria(Array, Array)
#3 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(31): CActiveRecord->findAll(Array)
#4 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionPage()
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('page')
#9 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/page')
#10 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/api/page?id=settgins
HTTP_REFERER=http://sitioblog.com/
---
2015/09/16 16:46:52 [error] [exception.CException] exception 'CException' with message 'Property "CDbCriteria.author" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:173
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\schema\CDbCriteria.php(160): CComponent->__set('author', 1)
#1 Z:\home\sitioblog.com\www\framework\db\schema\CDbCommandBuilder.php(588): CDbCriteria->__construct(Array)
#2 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(1474): CDbCommandBuilder->createCriteria(Array, Array)
#3 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(39): CActiveRecord->findAll(Array)
#4 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionBlog()
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('blog')
#9 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/blog')
#10 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/16 16:47:02 [error] [exception.CException] exception 'CException' with message 'Property "CDbCriteria.author" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:173
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\schema\CDbCriteria.php(160): CComponent->__set('author', 1)
#1 Z:\home\sitioblog.com\www\framework\db\schema\CDbCommandBuilder.php(588): CDbCriteria->__construct(Array)
#2 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(1474): CDbCommandBuilder->createCriteria(Array, Array)
#3 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(39): CActiveRecord->findAll(Array)
#4 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionBlog()
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('blog')
#9 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/blog')
#10 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/16 16:47:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "blog".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('blog')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/blog
---
2015/09/16 16:48:02 [error] [exception.CException] exception 'CException' with message 'Property "CDbCriteria.author" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:173
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\schema\CDbCriteria.php(160): CComponent->__set('author', 1)
#1 Z:\home\sitioblog.com\www\framework\db\schema\CDbCommandBuilder.php(588): CDbCriteria->__construct(Array)
#2 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(1474): CDbCommandBuilder->createCriteria(Array, Array)
#3 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(39): CActiveRecord->findAll(Array)
#4 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionBlog()
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('blog')
#9 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/blog')
#10 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/api/blog
---
2015/09/16 16:48:27 [error] [exception.CException] exception 'CException' with message 'Post and its behaviors do not have a method or closure named "findAllByAttribute".' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:266
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(227): CComponent->__call('findAllByAttrib...', Array)
#1 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(39): CActiveRecord->__call('findAllByAttrib...', Array)
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(39): Post->findAllByAttribute(Array)
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionBlog()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('blog')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/blog')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
---
2015/09/17 09:33:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://sitioblog.com/
---
2015/09/17 15:36:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "blog".' in Z:\home\sitioblog.com\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(270): CController->missingAction('blog')
#1 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('blog')
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/blog')
#3 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/17 15:36:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "blog".' in Z:\home\sitioblog.com\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(270): CController->missingAction('blog')
#1 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('blog')
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/blog')
#3 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/17 15:38:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "blog".' in Z:\home\sitioblog.com\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(270): CController->missingAction('blog')
#1 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('blog')
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/blog')
#3 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/17 15:38:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "blog".' in Z:\home\sitioblog.com\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(270): CController->missingAction('blog')
#1 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('blog')
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/blog')
#3 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/17 16:22:18 [error] [exception.CException] exception 'CException' with message 'ApiController cannot find the requested view "index".' in Z:\home\sitioblog.com\www\framework\web\CController.php:878
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(31): CController->render('index')
#2 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionPage()
#3 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('page')
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/page')
#8 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/api/page?id=index
HTTP_REFERER=http://sitioblog.com/
---
2015/09/17 16:22:27 [error] [exception.CException] exception 'CException' with message 'ApiController cannot find the requested view "index".' in Z:\home\sitioblog.com\www\framework\web\CController.php:878
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(31): CController->render('index')
#2 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionPage()
#3 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('page')
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/page')
#8 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/api/page?id=settings
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 09:30:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 09:44:35 [error] [exception.CException] exception 'CException' with message 'ApiController cannot find the requested view "null".' in Z:\home\sitioblog.com\www\framework\web\CController.php:878
Stack trace:
#0 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(31): CController->renderPartial('null', NULL, true)
#1 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionPage()
#2 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('page')
#6 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/page')
#7 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/api/page?id=null
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 10:58:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "blog".' in Z:\home\sitioblog.com\www\framework\web\CController.php:483
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(270): CController->missingAction('blog')
#1 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('blog')
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/blog/0')
#3 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/api/blog/0
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 11:56:08 [error] [exception.CException] exception 'CException' with message 'ApiController and its behaviors do not have a method or closure named "getJsonInput".' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:266
Stack trace:
#0 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(51): CComponent->__call('getJsonInput', Array)
#1 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(51): ApiController->getJsonInput()
#2 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#3 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('create')
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create')
#8 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 14:57:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2015/09/18 14:57:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2015/09/18 14:59:18 [error] [php] json_decode() expects parameter 1 to be string, array given (Z:\home\sitioblog.com\www\framework\web\helpers\CJSON.php:335)
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#1 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#3 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#4 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#5 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#6 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#7 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/blog
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (59)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:00:49 [error] [exception.CException] exception 'CException' with message 'ApiController and its behaviors do not have a method or closure named "getJsonInput".' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:266
Stack trace:
#0 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(51): CComponent->__call('getJsonInput', Array)
#1 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(51): ApiController->getJsonInput()
#2 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#3 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('create')
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create')
#8 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 15:03:06 [error] [php] include(author.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\sitioblog.com\www\framework\YiiBase.php:432)
Stack trace:
#0 unknown(0): spl_autoload_call()
#1 Z:\home\sitioblog.com\www\framework\YiiBase.php(303): class_exists()
#2 Z:\home\sitioblog.com\www\framework\validators\CValidator.php(174): import()
#3 Z:\home\sitioblog.com\www\framework\base\CModel.php(287): createValidator()
#4 Z:\home\sitioblog.com\www\framework\base\CModel.php(260): Post->createValidators()
#5 Z:\home\sitioblog.com\www\framework\base\CModel.php(547): Post->getValidators()
#6 Z:\home\sitioblog.com\www\framework\base\CModel.php(468): Post->getSafeAttributeNames()
#7 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(51): Post->setAttributes()
#8 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#9 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#10 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#11 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#12 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#13 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/blog
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (51)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:05:58 [error] [php] include(author.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\sitioblog.com\www\framework\YiiBase.php:432)
Stack trace:
#0 unknown(0): spl_autoload_call()
#1 Z:\home\sitioblog.com\www\framework\YiiBase.php(303): class_exists()
#2 Z:\home\sitioblog.com\www\framework\validators\CValidator.php(174): import()
#3 Z:\home\sitioblog.com\www\framework\base\CModel.php(287): createValidator()
#4 Z:\home\sitioblog.com\www\framework\base\CModel.php(260): Post->createValidators()
#5 Z:\home\sitioblog.com\www\framework\base\CModel.php(158): Post->getValidators()
#6 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(52): Post->validate()
#7 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#8 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#10 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#11 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#12 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/blog
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (52)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:06:20 [error] [php] include(author.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\sitioblog.com\www\framework\YiiBase.php:432)
Stack trace:
#0 unknown(0): spl_autoload_call()
#1 Z:\home\sitioblog.com\www\framework\YiiBase.php(303): class_exists()
#2 Z:\home\sitioblog.com\www\framework\validators\CValidator.php(174): import()
#3 Z:\home\sitioblog.com\www\framework\base\CModel.php(287): createValidator()
#4 Z:\home\sitioblog.com\www\framework\base\CModel.php(260): Post->createValidators()
#5 Z:\home\sitioblog.com\www\framework\base\CModel.php(158): Post->getValidators()
#6 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(52): Post->validate()
#7 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#8 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#10 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#11 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#12 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/blog
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (52)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:06:53 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL).
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (54)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:06:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL)' in Z:\home\sitioblog.com\www\framework\db\CDbCommand.php:358
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(54): CActiveRecord->save(false)
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('create')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 15:07:41 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL).
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (54)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:07:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL)' in Z:\home\sitioblog.com\www\framework\db\CDbCommand.php:358
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(54): CActiveRecord->save(false)
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('create')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 15:08:41 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL).
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (55)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:08:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL)' in Z:\home\sitioblog.com\www\framework\db\CDbCommand.php:358
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(55): CActiveRecord->save(false)
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('create')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 15:11:40 [warning] [application] Failed to set unsafe attribute "content" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (51)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:11:40 [warning] [application] Failed to set unsafe attribute "author" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (51)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:11:40 [warning] [application] Failed to set unsafe attribute "date" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (51)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:11:40 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL).
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (55)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:11:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL)' in Z:\home\sitioblog.com\www\framework\db\CDbCommand.php:358
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(55): CActiveRecord->save(false)
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('create')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 15:12:11 [warning] [application] Failed to set unsafe attribute "content" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (52)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:12:11 [warning] [application] Failed to set unsafe attribute "author" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (52)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:12:11 [warning] [application] Failed to set unsafe attribute "date" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (52)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:12:11 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL).
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (55)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:12:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL)' in Z:\home\sitioblog.com\www\framework\db\CDbCommand.php:358
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(55): CActiveRecord->save(false)
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('create')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 15:15:14 [warning] [application] Failed to set unsafe attribute "content" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (54)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:15:14 [warning] [application] Failed to set unsafe attribute "author" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (54)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:15:14 [warning] [application] Failed to set unsafe attribute "date" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (54)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:15:14 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL).
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (57)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:15:14 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL)' in Z:\home\sitioblog.com\www\framework\db\CDbCommand.php:358
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(57): CActiveRecord->save(false)
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('create')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 15:17:22 [warning] [application] Failed to set unsafe attribute "content" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (54)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:17:22 [warning] [application] Failed to set unsafe attribute "author" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (54)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:17:22 [warning] [application] Failed to set unsafe attribute "date" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (54)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:17:22 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL).
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (57)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:17:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`sitioblog`.`posts`, CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author`) REFERENCES `users` (`id`)). The SQL statement executed was: INSERT INTO `posts` (`id`) VALUES (NULL)' in Z:\home\sitioblog.com\www\framework\db\CDbCommand.php:358
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(57): CActiveRecord->save(false)
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('create')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 15:18:10 [error] [php] include(author.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\sitioblog.com\www\framework\YiiBase.php:432)
Stack trace:
#0 unknown(0): spl_autoload_call()
#1 Z:\home\sitioblog.com\www\framework\YiiBase.php(303): class_exists()
#2 Z:\home\sitioblog.com\www\framework\validators\CValidator.php(174): import()
#3 Z:\home\sitioblog.com\www\framework\base\CModel.php(287): createValidator()
#4 Z:\home\sitioblog.com\www\framework\base\CModel.php(260): Post->createValidators()
#5 Z:\home\sitioblog.com\www\framework\base\CModel.php(547): Post->getValidators()
#6 Z:\home\sitioblog.com\www\framework\base\CModel.php(468): Post->getSafeAttributeNames()
#7 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(54): Post->setAttributes()
#8 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#9 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#10 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#11 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#12 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#13 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/blog
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (54)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 15:18:27 [error] [exception.CException] exception 'CException' with message 'Property "CDateValidator.0" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:173
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\validators\CValidator.php(177): CComponent->__set('0', 'required')
#1 Z:\home\sitioblog.com\www\framework\base\CModel.php(287): CValidator::createValidator('date', Object(Post), 'content', Array)
#2 Z:\home\sitioblog.com\www\framework\base\CModel.php(260): CModel->createValidators()
#3 Z:\home\sitioblog.com\www\framework\base\CModel.php(547): CModel->getValidators()
#4 Z:\home\sitioblog.com\www\framework\base\CModel.php(468): CModel->getSafeAttributeNames()
#5 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(54): CModel->setAttributes(Array)
#6 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionCreate()
#7 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('create')
#11 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/create')
#12 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 15:25:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 16:25:52 [error] [exception.CException] exception 'CException' with message 'Property "User.posts" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:173
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(161): CComponent->__set('posts', 6)
#1 Z:\home\sitioblog.com\www\framework\base\CModel.php(607): CActiveRecord->__set('posts', 6)
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(54): CModel->offsetSet('posts', 6)
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionUser()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('user')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/user')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/user?id=1
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 16:42:32 [error] [exception.CException] exception 'CException' with message 'Property "Post.authorName" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:173
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(161): CComponent->__set('authorName', 'Demid Ganenko')
#1 Z:\home\sitioblog.com\www\framework\base\CModel.php(607): CActiveRecord->__set('authorName', 'Demid Ganenko')
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(42): CModel->offsetSet('authorName', 'Demid Ganenko')
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('list')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/list')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 16:42:43 [error] [exception.CException] exception 'CException' with message 'Property "Post.authorName" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:173
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(161): CComponent->__set('authorName', 'Demid Ganenko')
#1 Z:\home\sitioblog.com\www\framework\base\CModel.php(607): CActiveRecord->__set('authorName', 'Demid Ganenko')
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(42): CModel->offsetSet('authorName', 'Demid Ganenko')
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('list')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/list')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 16:49:48 [error] [exception.CException] exception 'CException' with message 'Property "Post.authorName" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:173
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(161): CComponent->__set('authorName', 'Demid Ganenko')
#1 Z:\home\sitioblog.com\www\framework\base\CModel.php(607): CActiveRecord->__set('authorName', 'Demid Ganenko')
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(42): CModel->offsetSet('authorName', 'Demid Ganenko')
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('list')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/list')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 16:50:35 [error] [exception.CException] exception 'CException' with message 'Property "Post._attributes" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('_attributes')
#1 Z:\home\sitioblog.com\www\framework\base\CModel.php(596): CActiveRecord->__get('_attributes')
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(44): CModel->offsetGet('_attributes')
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('list')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/list')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 16:55:27 [error] [exception.CException] exception 'CException' with message 'Property "Post.authorName" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:173
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(161): CComponent->__set('authorName', NULL)
#1 Z:\home\sitioblog.com\www\framework\base\CModel.php(607): CActiveRecord->__set('authorName', NULL)
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(46): CModel->offsetSet('authorName', NULL)
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('list')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/list')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 16:59:05 [error] [exception.CException] exception 'CException' with message 'Property "Post.authorName" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:173
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(161): CComponent->__set('authorName', 'Demid Ganenko')
#1 Z:\home\sitioblog.com\www\framework\base\CModel.php(607): CActiveRecord->__set('authorName', 'Demid Ganenko')
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(46): CModel->offsetSet('authorName', 'Demid Ganenko')
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('list')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/list')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 17:01:46 [error] [php] Object of class Post could not be converted to string (Z:\home\sitioblog.com\www\protected\controllers\ApiController.php:43)
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#1 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#3 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#5 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/blog
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (43)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 17:01:59 [error] [php] Object of class Post could not be converted to string (Z:\home\sitioblog.com\www\protected\controllers\ApiController.php:43)
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#1 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#2 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#3 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#5 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/blog
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (43)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 17:07:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:09:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:09:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:09:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:09:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:09:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:09:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:10:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:10:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:10:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://sitioblog.com/gii
---
2015/09/18 17:10:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2015/09/18 17:11:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/gii
---
2015/09/18 17:11:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:11:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:11:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:11:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:11:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/09/18 17:22:05 [error] [php] include(Post.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\sitioblog.com\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(39): spl_autoload_call()
#1 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#6 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/blog
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (39)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 17:22:05 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\sitioblog.com\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(56): spl_autoload_call()
#1 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionUser()
#2 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#6 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/user?id=1
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (56)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 17:22:17 [error] [php] include(Post.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\sitioblog.com\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(39): spl_autoload_call()
#1 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#6 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/blog
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (39)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 17:22:17 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (Z:\home\sitioblog.com\www\framework\YiiBase.php:432)
Stack trace:
#0 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(56): spl_autoload_call()
#1 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionUser()
#2 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 Z:\home\sitioblog.com\www\framework\web\CController.php(286): ApiController->runAction()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): ApiController->run()
#6 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\home\sitioblog.com\www\index.php(13): CWebApplication->run()
REQUEST_URI=/api/user?id=1
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (56)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 17:23:39 [error] [exception.CException] exception 'CException' with message 'Property "Post.authorName" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:173
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(161): CComponent->__set('authorName', NULL)
#1 Z:\home\sitioblog.com\www\framework\base\CModel.php(607): CActiveRecord->__set('authorName', NULL)
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(44): CModel->offsetSet('authorName', NULL)
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('list')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/list')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 17:30:13 [error] [exception.CException] exception 'CException' with message 'Property "Post.attirbutes" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('attirbutes')
#1 Z:\home\sitioblog.com\www\framework\base\CModel.php(596): CActiveRecord->__get('attirbutes')
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(44): CModel->offsetGet('attirbutes')
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('list')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/list')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 17:39:31 [error] [exception.CException] exception 'CException' with message 'Property "Post._attributes" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('_attributes')
#1 Z:\home\sitioblog.com\www\framework\base\CModel.php(596): CActiveRecord->__get('_attributes')
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(45): CModel->offsetGet('_attributes')
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('list')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/list')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 17:39:40 [error] [exception.CException] exception 'CException' with message 'Property "Post._attributes" is not defined.' in Z:\home\sitioblog.com\www\framework\base\CComponent.php:130
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\db\ar\CActiveRecord.php(145): CComponent->__get('_attributes')
#1 Z:\home\sitioblog.com\www\framework\base\CModel.php(596): CActiveRecord->__get('_attributes')
#2 Z:\home\sitioblog.com\www\protected\controllers\ApiController.php(45): CModel->offsetGet('_attributes')
#3 Z:\home\sitioblog.com\www\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#4 Z:\home\sitioblog.com\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 Z:\home\sitioblog.com\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 Z:\home\sitioblog.com\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(282): CController->run('list')
#8 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('api/list')
#9 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/blog
HTTP_REFERER=http://sitioblog.com/
---
2015/09/18 17:56:56 [warning] [application] Failed to set unsafe attribute "authorName" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (79)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/18 17:57:59 [warning] [application] Failed to set unsafe attribute "authorName" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (79)
in Z:\home\sitioblog.com\www\index.php (13)
2015/09/21 10:26:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://sitioblog.com/
---
2015/09/21 14:42:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in Z:\home\sitioblog.com\www\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\home\sitioblog.com\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 Z:\home\sitioblog.com\www\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\home\sitioblog.com\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://sitioblog.com/
---
2015/09/21 15:24:19 [warning] [application] Failed to set unsafe attribute "authorName" of "Post".
in Z:\home\sitioblog.com\www\protected\controllers\ApiController.php (79)
in Z:\home\sitioblog.com\www\index.php (13)
